### ISSUE TITLE
Widget does not render in Mx 6.2.0 when Render as HTML is set to No

### ISSUE THREAD

**Issue by David-Sanders** [mendix/CustomString#4]
In Mendix version 6.2.0, if the defaul property Render value as HTML is left as No, the widget does not render on the page.  If the property is set to Yes, the widget renders correctly

**Comment by Mcpoowl** [comment]
Just out of curiousity @JelteMX . Might this be the same cause as the one with the HTMLsnippet, which failed to render if the entered text wasn't a valid HTML tag? mendix/HTMLsnippet#6

**Comment by JelteMX** [comment]
That's a valid point @Mcpoowl. I think the problem lies [here](https://github.com/mendix/CustomString/blob/master/src/CustomString/widget/CustomString.js#L119). I'll check it out

**Comment by JelteMX** [comment]
Confirmed bug. Will implement a fix
